services:
  postgres:
    image: postgres:15
    container_name: spotify_db
    environment:
      POSTGRES_USER: abdullah
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: spotify_ai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
